CREATE OR REPLACE TABLE b_table (
    id INTEGER AUTOINCREMENT,
    type INTEGER NOT NULL CHECK (type BETWEEN 1 AND 5),
    name VARCHAR(100),
    created_date TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    status VARCHAR(20) DEFAULT 'ACTIVE'
);